### ISSUE TITLE
Broken images on the Philosophy link

### ISSUE THREAD

**Issue by pkoch** [demands/mx#13]
On https://wynnnetherland.com/journal/tmux-stateful-workspaces-for-frictionless-context-switching/, I see this: 
<img width="1440" alt="Screenshot 2021-03-23 at 11 12 42" src="https://user-images.githubusercontent.com/9627/112137857-b321f800-8bc8-11eb-882c-38afde4a9333.png">

For those wanting to know what they looked like, you can checkout [a copy on the way back machine](http://web.archive.org/web/20190502024236/https://wynnnetherland.com/journal/tmux-stateful-workspaces-for-frictionless-context-switching/).

**Comment by pengwynn** [comment]
@pkoch Thanks for the heads up. [Fixed](https://wynnnetherland.com/journal/tmux-stateful-workspaces-for-frictionless-context-switching/).
